package io.reactivesw.message.client.core;

import java.io.Serializable;
import java.util.UUID;

/**
 * Message for publish or receive.
 * All messages in our system should be an json.
 */
public class Message implements Serializable {

  /**
   * auto generated serial version id.
   */
  private static final long serialVersionUID = 8815878036860971332L;

  /**
   * unique message id.
   */
  private String id;

  /**
   * sequence number used to detect the order of the message.
   */
  private String sequenceNumber;

  /**
   * create time.
   */
  private long createTime;

  /**
   * message expire time. if expire is 0, then this message is will never expired.
   */
  private long expire;

  /**
   * external id, can set the id generated by broker.
   */
  private String externalId;

  /**
   * message version.
   */
  private long version;

  /**
   * message data.
   */
  private Object data;

  /**
   * message build with data.
   * uuid will be generated with UUID.
   *
   * @param data serializable data
   * @return Message
   */
  public static Message build(Object data) {
    Message msg = new Message();
    msg.id = UUID.randomUUID().toString();
    msg.data = data;
    msg.createTime = System.currentTimeMillis();
    return msg;
  }

  /**
   * message build with message id and data.
   *
   * @param id      message id
   * @param data data.
   * @return Message
   */
  public static Message build(String id, Object data) {
    Message msg = new Message();
    msg.id = id;
    msg.data = data;
    msg.createTime = System.currentTimeMillis();
    return msg;
  }

  /**
   * message build with message id and data.
   *
   * @param id             message id
   * @param data        data.
   * @param sequenceNumber String
   * @return Message
   */
  public static Message build(String id, String sequenceNumber, Object data) {
    Message msg = new Message();
    msg.id = id;
    msg.sequenceNumber = sequenceNumber;
    msg.data = data;
    msg.createTime = System.currentTimeMillis();
    return msg;
  }

  /**
   * message build with message id and data.
   *
   * @param id             message id
   * @param data        Serializable.
   * @param sequenceNumber String
   * @param createTime     long
   * @return Message
   */
  public static Message build(String id, String sequenceNumber, long createTime, Object
      data) {
    Message msg = new Message();
    msg.id = id;
    msg.sequenceNumber = sequenceNumber;
    msg.data = data;
    msg.createTime = createTime;
    return msg;
  }


  /**
   * message build with message id and data.
   *
   * @param id             message id
   * @param data        Serializable.
   * @param sequenceNumber String
   * @param createTime     long
   * @return Message
   */
  public static Message build(String id, String sequenceNumber, long createTime, long version,
                              Object data) {
    Message msg = new Message();
    msg.id = id;
    msg.sequenceNumber = sequenceNumber;
    msg.data = data;
    msg.createTime = createTime;
    msg.version = version;
    return msg;
  }

  /**
   * message build with message id and data.
   *
   * @param id             message id
   * @param data        Serializable.
   * @param sequenceNumber String
   * @param createTime     long
   * @return Message
   */
  public static Message build(String id, String sequenceNumber, long createTime, long version,
                              long expire, Object data) {
    Message msg = new Message();
    msg.id = id;
    msg.sequenceNumber = sequenceNumber;
    msg.data = data;
    msg.createTime = createTime;
    msg.version = version;
    msg.expire = expire;
    return msg;
  }

  /**
   * get id.
   *
   * @return String
   */
  public String getId() {
    return id;
  }

  /**
   * set id.
   *
   * @param id String
   */
  public void setId(String id) {
    this.id = id;
  }

  /**
   * get sequence number.
   *
   * @return String
   */
  public String getSequenceNumber() {
    return sequenceNumber;
  }

  /**
   * set sequence number.
   *
   * @param sequenceNumber String
   */
  public void setSequenceNumber(String sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  /**
   * get create time.
   *
   * @return long
   */
  public long getCreateTime() {
    return createTime;
  }

  /**
   * set create time.
   *
   * @param createTime long
   */
  public void setCreateTime(long createTime) {
    this.createTime = createTime;
  }

  /**
   * get expire.
   *
   * @return long
   */
  public long getExpire() {
    return expire;
  }

  /**
   * set expire.
   *
   * @param expire long
   */
  public void setExpire(long expire) {
    this.expire = expire;
  }

  /**
   * get external id.
   *
   * @return String
   */
  public String getExternalId() {
    return externalId;
  }

  /**
   * set external id.
   *
   * @param externalId String
   */
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  /**
   * get version.
   *
   * @return long
   */
  public long getVersion() {
    return version;
  }

  /**
   * set version.
   *
   * @param version long
   */
  public void setVersion(long version) {
    this.version = version;
  }

  /**
   * get data.
   *
   * @return set data.
   */
  public Object getData() {
    return data;
  }

  /**
   * set data.
   *
   * @param data Serializable
   */
  public void setData(Object data) {
    this.data = data;
  }
}
